version: "3"
services: 
  node:
    image: rattymyles/docker-express-api:latest
    container_name: express-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "mariadb"
      DB_PORT: 3306
      DB_USER: "app_user"
      DB_PASSWORD: "Password123!"
      DB_DATABASE: "todo"
    networks:
      - docker-service
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: docker-mariadb
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "Password123!"
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db
      - ./demo.sql:/docker-entrypoint-initdb.d/demo.sql

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local
